server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: vehicle-brand-service
          uri: lb://vehicle-brand-service
          predicates:
            - Path=/api/vehicleBrands/**
          filters:
            - StripPrefix=1
        - id: vehicle-type-service
          uri: lb://vehicle-type-service
          predicates:
            - Path=/api/vehicleTypes/**
          filters:
            - StripPrefix=1
        - id: vehicle-engine-service
          uri: lb://vehicle-engine-service
          predicates:
            - Path=/api/vehicleEngines/**
          filters:
            - StripPrefix=1
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/vehicles/**
          filters:
            - StripPrefix=1
        - id: brand-discount-service
          uri: lb://brand-discount-service
          predicates:
            - Path=/api/brandDiscounts/**
          filters:
            - StripPrefix=1
        - id: discount-service
          uri: lb://discount-service
          predicates:
            - Path=/api/discounts/**
          filters:
            - StripPrefix=1
        - id: repair-type-service
          uri: lb://repair-type-service
          predicates:
            - Path=/api/repairTypes/**
          filters:
            - StripPrefix=1
        - id: surcharge-service
          uri: lb://surcharge-service
          predicates:
            - Path=/api/surcharges/**
          filters:
            - StripPrefix=1
