server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: vehicle-service
          uri: lb://vehicle-service:8099
          predicates:
            - Path=/api/vehicles/**
        - id: repair-type-service
          uri: lb://repair-type-service:8094
          predicates:
            - Path=/api/repairTypes/**
        - id: summary1-service
          uri: lb://summary1-service:8095
          predicates:
            - Path=/api/summary1/**
        - id: repair-service
          uri: lb://repair-service:8098
          predicates:
            - Path=/api/repairs/**
