server:
  port: ${PORT:${SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: eureka-service
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  application:
    name: repair-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://repair-db-service:5432/autofix_repair
    username: postgres
    password: 1234
  sql:
    init:
      mode: never
