server:
  port: 8091
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  application:
    name: vehicle-brand-service
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/autofix_vehiclebrand
    username: postgres
    password: 1234
  sql:
    init:
      mode: never
