apiVersion: apps/v1
kind: Deployment
metadata:
  name: brand-discount-deployment
  labels:
    app: brand-discount-deployment
spec:
  selector:
    matchLabels:
      app: brand-discount-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: brand-discount-deployment
    spec:
      containers:
        - name: brand-discount-service
          image: bcanales/brand-discount-service
          ports:
            - containerPort: 8095