apiVersion: apps/v1
kind: Deployment
metadata:
  name: summary1-deployment
  labels:
    app: summary1-deployment
spec:
  selector:
    matchLabels:
      app: summary1-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: summary1-deployment
    spec:
      containers:
        - name: summary1-service
          image: bcanales/summary1-service
          ports:
            - containerPort: 8082