apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehicle-type-deployment
  labels:
    app: vehicle-type-deployment
spec:
  selector:
    matchLabels:
      app: vehicle-type-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: vehicle-type-deployment
    spec:
      containers:
        - name: vehicle-type-service
          image: bcanales/vehicle-type-service
          ports:
            - containerPort: 8093