server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/benjaminCanalesC/autofix-ms-backend
          search-paths: config-data
          default-label: main
  application:
    name: config-service
